name: News Aggregator

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install feedparser requests
        
      - name: Run the bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
